version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../habit-tracker-backend
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:P@ssw0rd@db:5432/postgres
    depends_on:
      - db
    volumes:
      - ../habit-tracker-backend:/app
    command: npm run start:dev

  frontend:
    build: ../habit-tracker-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ../habit-tracker-frontend:/app
    command: /bin/sh -c "npm run build && npm start"

volumes:
  postgres_data:
