version: '3.8'
services:
  backend:
    build: ./habit-tracker-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:P@ssw0rd@db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./habit-tracker-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
