version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: habittracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  backend:
    build: ../habit-tracker-backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  frontend:
    build: ../habit-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
